config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  resources :characters

  # get '/universes' => 'universes#index', as: 'universes'
  resources :universes
  get '/characters/all/d3json' => 'characters#d3json'
  get '/characters/:id/addRelation' => 'characters#addRelation', as: 'add_relation'
  post '/characters/:id' => 'characters#createRelation', as: 'create_Relation'
  delete '/characters/deleteAffiliation/:id' => 'characters#destroyRelation'
  get '/characters/:characterid/editQualities/:qualityid' => 'characters#editQualities', as: 'qualities'
  post '/characters/:characterid/editQualities/:qualityid' => 'characters#updateQualities'
  get '/characters/:id/addQuality' => 'characters#addQuality', as: 'add_quality'
  post '/characters/:id/addQuality' => 'characters#postQuality', as: 'post_quality'
  delete '/characters/:characterid/destroyQualities/:qualityid' => 'characters#destroyQuality', as: 'destroy_quality'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get '/test' => 'characters#testJSON'
end

app/models/story.rb
class Story < ApplicationRecord
  has_and_belongs_to_many :character
  has_many :stories_sequence
  has_many :stories_note
  belongs_to :universe
  belongs_to :user
  belongs_to :genre
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.where(user_id: current_user.id)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show

  end

  # GET /stories/new
  def new
    # @story = Story.new
    @universes = Universe.where(user_id: current_user.id)
    @genres = Genre.all
    @user_id = current_user.id
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
    @universes = Universe.where(user_id: current_user.id)
    @genres = Genre.all
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params.merge(user_id: current_user.id))

    @story.save
    redirect_to stories_path
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:name, :universe_id, :genre_id, :summary, :user_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :universe_id %>
    <%= form.number_field :universe_id %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<div class="contain">
	<h1>Editing Story</h1>

	<%= form_with scope: :story, model: @story, local: true do |form| %>

		<%= form.collection_select :universe_id, @universes, :id, :name %> <br/>
		<%= form.collection_select :genre_id, @genres, :id, :name %>

		<p>
	    <%= form.label :name %><br>
	    <%= form.text_field :name %>
	  </p>



	  <p>
	    <%= form.label :summary %><br>
	    <%= form.text_area :summary %>
	  </p>


	  <p>
	    <%= form.submit :class => 'submit'%>
	  </p>
	<% end %>


	<%= link_to 'Show', @story %>
	<%= link_to 'Back', stories_path %>
</div>
<%= stylesheet_link_tag 'edit' %>

app/views/stories/index.html.erb
<div class="show">
	<div class="headerText">
		<h1>STORIES</h1>
	</div>

	<div class="tableDiv">
	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Universe</th>
	      <th>Genre</th>
	      <!-- <th>Summary</th> -->
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @stories.each do |story| %>
	      <tr>
	        <td><%= story.name %></td>
	        <td><%= story.universe.name %></td>
	        <td><%= story.genre.name %></td>
	        <!-- <td><%= story.summary %></td> -->
	        <td class="linkButton"><%= link_to 'Show', story %></td>
	        <td class="linkButton"><%= link_to 'Edit', edit_story_path(story) %></td>
	        <td class="linkButton"><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	</div>

	<br>

	<div class="createNew"><%= link_to 'New Story', new_story_path %></div>
</div>
<%= stylesheet_link_tag 'template' %>

app/views/stories/new.html.erb
<div class="contain">
	<h1>New Story</h1>

	<%= form_with scope: :story, url: stories_path, local: true do |form| %>


		<h2>UNIVERSE</h2>
		<%= form.collection_select :universe_id, @universes, :id, :name %>


		<h2>GENRE</h2>
		<%= form.collection_select :genre_id, @genres, :id, :name %>


		<p>
	    <%= form.label :name %><br>
	    <%= form.text_field :name %>
	  </p>



	  <p>
	    <%= form.label :summary %><br>
	    <%= form.text_area :summary %>
	  </p>


	    <%= form.submit :class => "submit"%>
	<% end %>

	<%= link_to 'Back', stories_path %>
</div>

<%= stylesheet_link_tag 'new' %>

app/views/stories/show.html.erb
<div class="glitchDiv">
	<h1 class="name glitch romance comedy fantasy" data-text="<%= @story.name %>">
	  <%= @story.name %>
	</h1>
</div>


<div class="romanceBody scifiBody comedyBody fantasyBody body">



		<div class="bird-container bird-container--one">
			<div class="bird bird--one"></div>
		</div>

		<div class="bird-container bird-container--two">
			<div class="bird bird--two"></div>
		</div>

		<div class="bird-container bird-container--three">
			<div class="bird bird--three"></div>
		</div>

		<div class="bird-container bird-container--four">
			<div class="bird bird--four"></div>
		</div>


	<p>
	  <strong>Universe:</strong>
	  <%= @story.universe.name %>
	</p>

	<p>
	  <strong>Genre:</strong>
	  <%= @story.genre.name %>
	</p>

	<p>
	  <strong>Summary:</strong>
	  <%= @story.summary %>
	</p>

	<p>
	  <strong>Characters:</strong>
	  <% @story.character.each do |character| %>
	  <p class="charname"><%= link_to character.name, character %></p>
	  <% end %>
	</p>

	<% if @story.genre.name == "Sci-fi" %>
		<%= stylesheet_link_tag 'scifi' %>
	<% elsif @story.genre.name == "Romance" %>
		<%= stylesheet_link_tag 'romance' %>
		<%= javascript_pack_tag 'romance' %>
	<% elsif @story.genre.name == "Comedy" %>
		<%= stylesheet_link_tag 'comedy' %>
	<% elsif @story.genre.name == "Fantasy" %>
		<%= stylesheet_link_tag 'fantasy' %>
	<% end %>

	<%= stylesheet_link_tag 'show' %>

</div>

<div class="links">
	<%= link_to 'Edit', edit_story_path(@story), :class => 'tags' %>
	<%= link_to 'Back', stories_path, :class => 'tags' %>
</div>