config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  resources :characters

  # get '/universes' => 'universes#index', as: 'universes'
  resources :universes
  get '/characters/all/d3json' => 'characters#d3json'
  get '/characters/:id/addRelation' => 'characters#addRelation', as: 'add_relation'
  post '/characters/:id' => 'characters#createRelation', as: 'create_Relation'
  delete '/characters/deleteAffiliation/:id' => 'characters#destroyRelation'
  get '/characters/:characterid/editQualities/:qualityid' => 'characters#editQualities', as: 'qualities'
  post '/characters/:characterid/editQualities/:qualityid' => 'characters#updateQualities'
  get '/characters/:id/addQuality' => 'characters#addQuality', as: 'add_quality'
  post '/characters/:id/addQuality' => 'characters#postQuality', as: 'post_quality'
  delete '/characters/:characterid/destroyQualities/:qualityid' => 'characters#destroyQuality', as: 'destroy_quality'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get '/test' => 'characters#testJSON'
end

app/models/character.rb
require 'set'

class Character < ApplicationRecord
  has_and_belongs_to_many :story
  belongs_to :user

  has_many :relationships


  has_many :follower_relationships, foreign_key: :character2, class_name: 'Relationship'
  has_many :followers, through: :follower_relationships, source: :follower


  has_many :following_relationships, foreign_key: :character_id, class_name: 'Relationship'
  has_many :following, through: :following_relationships, source: :following

  has_many :quality

  def characterRelationship
    @relationship = Relationship.where('character_id = ? or character2 = ?', self.id, self.id)

    relationHash = {}

    @relationship.each do |relation|
      @character = Character.where(id: relation.character_id)[0]

      charName = @character.name.to_s
      if charName == self.name
        @character = Character.where(id: relation.character2)[0]
        if @character != nil
          @relation = relation
          charName = @character.name.to_s
          relationHash[charName] = @relation
        end
      elsif charName != self.name
        if @character != nil
          @relation = relation
          relationHash[charName] = @relation
        end
      end
    end
    return relationHash
  end

  def notRelated
    @relationship = characterRelationship.keys
    @allCharacters = Character.where.not(id: self.id)
    @notRelated = @allCharacters.select do |x|
      !@relationship.include?(x.name)
    end
    return @notRelated
  end

  def destroyRelation
    @exist = Relationship.where(character_id: self.id).or(Relationship.where(character2: self.id))
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def testJSON
    @@data = File.read("#{Rails.root}/app/javascript/packs/d3Graph/test.json")
    render :json => @@data
  end

  # GET /characters
  # GET /characters.json
  def index
    @user_id = current_user.id
    @characters = Character.where(user_id: @user_id)
    @relationship = Relationship.all
    # render plain: current_user.id
    # render :layout => false
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @characters = @character.characterRelationship


    @character_id = params[:id]

    # render plain: @relationships.inspect
    @qualities = @character.quality

    respond_to do |format|
      format.json {
          render :json => @character,
          include: :user
      }

      format.html
    end
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
    @user_id = current_user.id
    @stories = Story.where(user_id: @user_id)
    # render plain: @stories.inspect

    # @stories = Story.all
    # @relationship = CharactersStory.where(:character)
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update

    @character = Character.find(params[:id])
    @character.update(character_params)
    redirect_to characters_path
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @exist = Relationship.where(character_id: params[:id]).or(Relationship.where(character2: params[:id]))
    # @data = @character.merge(@exist)
    # render plain: @exist.inspect
    Quality.where(character_id: params[:id]).delete_all
    @character.destroy


    Relationship.where(id: @exist.map(&:id)).delete_all
    redirect_to characters_path

    # respond_to do |format|
    #   format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  def addRelation
    @character = Character.find(params[:id])
    @notRelated = @character.notRelated
  end

  def createRelation
    @character = Character.find(params[:id])
    @relation_params = relation_params.merge(character2: @character.id, user_id: current_user.id)
    @newRelation = Relationship.new(@relation_params)
    respond_to do |format|
      if @newRelation.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroyRelation
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to characters_path
  end

  def d3json
    @user_id = current_user.id
    @characters = Character.where(user_id: @user_id)
    @relationships = Relationship.where(user_id: @user_id)
    @data = {}
    @data[:nodes] = @characters.select(:id,:name)
    @data[:links] = @relationships
    render json: @data

  end

  def editQualities
    @quality = Quality.find(params[:qualityid])
  end

  def updateQualities
    @quality = Quality.find(params[:qualityid])
    @id = params[:characterid]
    @quality.update(quality_params)
    redirect_to "/characters/#{@id}"
  end

  def addQuality
    @character_id = params[:id]
  end

  def postQuality
    @character_id = params[:id]
    @data = quality_params.merge(:character_id => @character_id)
    @quality = Quality.new(@data)
    respond_to do |format|
      if @quality.save
        format.html { redirect_to "/characters/#{@character_id}", notice: 'Quality was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroyQuality
    @quality_id = params[:qualityid]
    @id = params[:characterid]
    @quality = Quality.find(@quality_id)
    @quality.destroy
    redirect_to "/characters/#{@id}"
    # render plain: @quality.inspect
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :story_ids => [])
    end

    def relation_params
      params.require(:character).permit(:character_id,:affiliation)
    end

    def quality_params
      params.require(:quality).permit(:quality,:value)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attribute %>
    <%= form.text_field :attribute %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.number_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/addQuality.html.erb
<div class="contain">
	<h1>New Qualities</h1>

	<%= form_with scope: :quality, url: post_quality_path, local: true do |form| %>
		<p>
	    <%= form.label :quality %><br>
	    <%= form.text_field :quality %>
	  </p>



	  <p>
	    <%= form.label :value %><br>
	    <%= form.text_area :value %>
	  </p>


	    <%= form.submit 'Save Quality', :class => "submit" %>

	<% end %>
</div>
<%= stylesheet_link_tag 'new' %>

app/views/characters/addRelation.html.erb
<div class="contain">
	<h1><%= @character.name %> </h1>

	<%= form_with scope: :character, url: create_Relation_path, local: true do |form| %>
		<p class="oneDiv">Character:
		<%= form.collection_select :character_id, @notRelated, :id, :name %>
		</p>

		<p class="oneDiv">
	    <%= form.label :affiliation %>
	    <%= form.text_field :affiliation, :required => 'required'%>
	  </p>


	  	<%= form.submit :class => "submit"%>

	<% end %>

	<%= link_to "Back", characters_path %>

</div>
<%= stylesheet_link_tag 'edit' %>

app/views/characters/edit.html.erb
<div class="contain">
	<h1>Editing Character</h1>

	<%= form_with scope: :character, model: @character, local: true do |form| %>

		<div class="checkBox">
			<%= form.collection_check_boxes :story_ids, @stories, :id, :name  do |story|%>
				<p>
					<%= story.check_box %>
					<%= story.label %>
				</p>
			<% end%>
		</div>

		<div class="formName">
	    <%= form.label :name %>
	    <%= form.text_field :name %>
	  </div>


	    <%= form.submit :class => "submit"%>

	<% end %>

	<%= link_to 'Back', @character %>
	<%= link_to 'Home', characters_path %>
</div>
<%= stylesheet_link_tag 'edit' %>

app/views/characters/editQualities.html.erb
<div class="contain">
	<h1>Editing Qualities</h1>
	<%= form_with scope: :quality, model: @character, local: true do |form| %>

		<div class="formName">
	    <%= form.label :quality %>
	    <%= form.text_field :quality %>
	  </div>

	  <div class="formName">
	    <%= form.label :value %>
	    <%= form.text_field :value %>
	  </div>

	    <%= form.submit :class => 'submit' %>
	<% end %>
</div>
<%= stylesheet_link_tag 'edit' %>

app/views/characters/index.html.erb
<div class="show">
	<div class="headerText">
		<h1>CHARACTERS</h1>
	</div>

	<!-- <%= javascript_pack_tag 'hello_react' %> -->
	<div>
		<h1 class="rls" id="rls">Show Relationship Chart</h1>
		<div id="d3div">
			<%= javascript_pack_tag 'd3Graph/test.js' %>
		</div>
	</div>

	<div class="tableDiv">
	<table>
	  <thead>
	    <tr>
	      <!-- <th>Name</th> -->
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @characters.each do |character| %>
	      <tr>
	        <td><%= character.name %></td>
	        <td class="linkButton"><%= link_to 'Show', character %></td>
	        <td class="linkButton"><%= link_to 'Edit', edit_character_path(character) %></td>
	        <td class="linkButton"><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	</div>

	<div class="createNew"><%= link_to 'New Character', new_character_path %></div>



</div>

<%= stylesheet_link_tag 'template' %>

app/views/characters/new.html.erb
<div class="contain">
<h1>New Character</h1>

<%= form_with scope: :character, url: characters_path, local: true do |form| %>

	<p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

    <%= form.submit :class => "submit" %>
<% end %>

<%= link_to 'Back', characters_path %>
</div>

<%= stylesheet_link_tag 'new' %>

app/views/characters/show.html.erb
<div class="show">


	<h1 class="name"><%= @character.name %></h1>

	<div class="contain">
	  <h1><strong>Stories</strong></h1>
	  <% @character.story.each do |story| %>
	  <p><%= story.name %></p>
	  <% end %>
	</div>

	<div class="contain">
	  <h1><strong>Qualities:</strong></h1>
	  <% @qualities.each do |quality| %>
	  	<p><%=quality.quality%>: <%=quality.value%>
	  	<%= link_to 'Edit', qualities_path(@character,quality) %>
	  	<%= link_to 'Delete', destroy_quality_path(@character,quality), method: :delete, data: { confirm: 'Are you sure?' } %>
	  	</p>
	  <% end %>
	  <%= link_to 'Add Qualities', add_quality_path %></p>
	</div>

	<div class="contain">
		<h1><strong>Relationships:</strong></h1>


		<% @characters.each do |key,value| %>
			<p><%=key%>: <%= value.affiliation %>
			<%=link_to 'Destroy', "/characters/deleteAffiliation/#{value.id}" , method: :delete, data: { confirm: 'Are you sure?' }%>
			</p>
		<% end %>


		<span class="add"><%= link_to 'Add relationship', add_relation_path %></span>
	</div>

	<div class="links">
	<%= link_to 'Edit', edit_character_path(@character) %> |
	<%= link_to 'Back', characters_path %>
	</div>


	<br/>


</div>
<%= stylesheet_link_tag 'shows' %>