config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  resources :characters

  # get '/universes' => 'universes#index', as: 'universes'
  resources :universes
  get '/characters/all/d3json' => 'characters#d3json'
  get '/characters/:id/addRelation' => 'characters#addRelation', as: 'add_relation'
  post '/characters/:id' => 'characters#createRelation', as: 'create_Relation'
  delete '/characters/deleteAffiliation/:id' => 'characters#destroyRelation'
  get '/characters/:characterid/editQualities/:qualityid' => 'characters#editQualities', as: 'qualities'
  post '/characters/:characterid/editQualities/:qualityid' => 'characters#updateQualities'
  get '/characters/:id/addQuality' => 'characters#addQuality', as: 'add_quality'
  post '/characters/:id/addQuality' => 'characters#postQuality', as: 'post_quality'
  delete '/characters/:characterid/destroyQualities/:qualityid' => 'characters#destroyQuality', as: 'destroy_quality'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get '/test' => 'characters#testJSON'
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  before_action :authenticate_user!
  def index
    @universes = Universe.where(user_id: current_user.id)
  end

  def show
    @universe = Universe.find(params[:id])

  end

  def new
    @universe = Universe.new
    @user_id = current_user.id
  end

  def edit
    @universe = Universe.find(params[:id])
  end

  def create
    @universe = Universe.new(universe_params.merge(user_id: current_user.id))
    @universe.save
    redirect_to universes_path
  end

  def update
    @universe = Universe.find(params[:id])
    @universe.update(universe_params)
    redirect_to universes_path
  end

  def destroy
    @universe = Universe.find(params[:id])
    @universe.destroy
    respond_to do |format|
      format.html { redirect_to universes_url, notice: 'Universe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def universe_params
      params.require(:universe).permit(:name, :description)
    end
end

app/views/universes/edit.html.erb
<div class="contain">
	<h1>Editing Universe</h1>

	<%= form_with scope: :universe, model: @universe, local: true do |form| %>

		<p>
	    <%= form.label :name %><br>
	    <%= form.text_field :name %>
	  </p>

	  <p>
	    <%= form.label :description %><br>
	    <%= form.text_area :description %>
	  </p>


	  <p>
	    <%= form.submit :class => 'submit'%>
	  </p>
	<% end %>

	<%= link_to 'Show', @universe %>
	<%= link_to 'Back', universes_path %>
</div>
<%= stylesheet_link_tag 'edit' %>

app/views/universes/index.html.erb
<div class="show">
	<div class="headerText">
		<h1>UNIVERSES</h1>
	</div>

	<div class="tableDiv">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<!-- <th>Description</th> -->
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @universes.each do |universe| %>
					<tr>
						<td><%= universe.name %></td>
						<!-- <td><%= universe.description %></td> -->
						<td class="linkButton"><%= link_to 'Show', universe %></td>
		        <td class="linkButton"><%= link_to 'Edit', edit_universe_path(universe) %></td>
		        <td class="linkButton"><%= link_to 'Destroy', universe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="createNew"><%= link_to 'New Universe', new_universe_path %></div>
</div>

<%= stylesheet_link_tag 'template' %>

app/views/universes/new.html.erb
<div class="contain">
<h1>New Universe</h1>

<%= form_with scope: :universe, url: universes_path, local: true do |form| %>

	<p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>



    <%= form.submit :class => "submit" %>

<% end %>

<%= link_to 'Back', universes_path %>
</div>

<%= stylesheet_link_tag 'new' %>

app/views/universes/show.html.erb
<div class="show">
	<h1 class="name"><%= @universe.name %></h1>

	<div class="contain">
	  <h1><strong>Description:</strong></h1>
	  <p><%= @universe.description %></p>
	</div>

	<div class="contain">
		<h1><strong>List of stories:</strong></h1>
		<% @universe.story.each do |story| %>
			<p><%= link_to story.name, story_path %></p>
		<% end %>
	</div>

	<div class="links">
		<%= link_to 'Edit', edit_universe_path(@universe) %> |
		<%= link_to 'Back', universes_path %>
	</div>
</div>

<%= stylesheet_link_tag 'shows' %>